/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../altair.json.  Do not edit it directly.

#pragma once
#include "seeed_mt3620_mdb.h"

// Network Connected
#define AZURE_CONNECTED_LED SEEED_MT3620_MDB_USER_LED

// MT3620 RDB: LED RED
#define LED_RED SEEED_MT3620_MDB_J1_PIN3_GPIO6

// MT3620 RDB: LED GREEN
#define LED_GREEN SEEED_MT3620_MDB_J1_PIN7_GPIO10

// MT3620 RDB: LED BLUE
#define LED_BLUE SEEED_MT3620_MDB_J2_PIN15_GPIO35

// NOT USED
#define ISU2 SEEED_MT3620_MDB_J1_ISU0_I2C

// NOT USED
#define BUTTON_A SEEED_MT3620_MDB_J1_PIN1_GPIO4

// NOT USED
#define BUTTON_B SEEED_MT3620_MDB_J1_PIN2_GPIO5

// NOT USED
#define SWITCHES_LOAD SEEED_MT3620_MDB_J1_PIN11_GPIO34

// NOT USED
#define SWITCHES_CHIP_SELECT SEEED_MT3620_MDB_J1_PIN5_GPIO8

// NOT USED
#define LED_MASTER_RESET SEEED_MT3620_MDB_J1_PIN6_GPIO9

// NOT USED
#define LED_STORE SEEED_MT3620_MDB_J2_PIN13_GPIO31

// NOT USED
#define LED_OUTPUT_ENABLE SEEED_MT3620_MDB_J1_PIN10_GPIO32

// Ignored on non Avnet boards
#define AVNET_LIGHT_SENSOR SEEED_MT3620_MDB_ADC_CONTROLLER0

